#!/usr/bin/env bash
# Script that installs Nginx server and redirects /redirect_me
apt-get -y update
apt-get -y install nginx
echo "Hello World" > /var/www/html/index.nginx-debian.html 
echo "Ceci n'est pas une page" > /usr/share/nginx/html/custom_404.html
sed -i "s/server_name _;/server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/Adexbobo23 permanent;\n\n\terror_page 404 \/custom_404.html;\n\tlocation = \/custom_404.html {\n\t\troot \/usr\/share\/nginx\/html;\n\t\tinternal;\n\t}/" /etc/nginx/sites-available/default
service nginx start
